# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'versi-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for versi-app
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod 'TweeTextField'
  pod "PulsingHalo"
  pod 'SDWebImage', '~> 4.0'
  pod 'Lightbox' 
  pod 'Firebase/Analytics'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics'
  pod 'Firebase/Performance'
end
