# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'versi-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for versi-app
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'TweeTextField'
  pod 'SDWebImage', '~> 4.0'
  pod 'Lightbox'
  pod 'Clarifai'
  pod 'PopupDialog', '~> 1.0.0'
end
